version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
      networks:
        - mern-app

networks:
  mern-app:
    driver: bridge
