version: "3"

services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql8
    volumes:
      - ./MySql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rdt
      MYSQL_DATABASE: rocheemptydb
      MYSQL_USER: ake43
      MYSQL_PASSWORD: rdt
    ports:
      - 3306:3306
    networks:
      - mern-app

  mysql57:
    image: mysql:5.7.34
    container_name: mysql56
    volumes:
      - ./MySql/data56:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rdt
      MYSQL_DATABASE: rocheemptydb
      MYSQL_USER: ake43
      MYSQL_PASSWORD: rdt
    ports:
      - 3307:3306
    networks:
      - mern-app


  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8081:80
    links:
      - mysql
    depends_on:
      - mysql
    environment:
      PMA_PORT: 3306
      PMA_HOST: mysql
      MYSQL_USERNAME: ake43
      MYSQL_ROOT_PASSWORD: rdt
    networks:
      - mern-app

  postgres:
    image: postgres:13.2
    container_name: postgres
    volumes:
        - ./Postgres/data:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=rocheemptydb
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=rdt
    networks:
        - mern-app
    ports:
        - 5432:5432
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    links: 
        - postgres
    depends_on:
        - postgres
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: ake43@hotmail.com
        PGADMIN_DEFAULT_PASSWORD: 'rdt'
    ports:
        - 8082:80
    networks:
        - mern-app

  postgresapi:
    image: postgrest/postgrest
    container_name: postgresapi
    ports:
        - "4000:3000"
    links:
        - postgres
    depends_on: 
      - postgres
    environment:
        PGRST_DB_URI: postgres://root:rdt:5432/rocheemptydb
        PGRST_DB_SCHEMA: public
        PGRST_DB_ANON_ROLE: root #In production this role should not be the same as the one used for the connection
        PGRST_SERVER_PROXY_URI: "http://127.0.0.1:4000"
    depends_on:
        - postgres
    networks:
        - mern-app

  mongo:
    image: mongo
    container_name: mongo
    ports:
        - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rdt
      MONGO_INITDB_DATABASE: rocheemptydb
    networks:
        - mern-app
    volumes:
        - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT : 27017
      #ME_CONFIG_MONGODB_AUTH_DATABASE | 'db' 
      #ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rdt
    links: 
      - mongo
    depends_on: 
      - mongo
    networks:
      - mern-app

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80

networks:
  mern-app:
    driver: bridge
volumes:
  postgres-data:
  pgadmin-data:
  mysql-data:
  mongo-data:
  redis-data:
  couchdb-data:
